#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f ~/.xprofile ] && . ~/.xprofile

# hide the mouse cursor when idle
unclutter -noevents -idle 2 &

# manage ssh keys
eval (ssh-agent -c)

# the bottom status bar
xmobar &

# notification popups
dunst &

# set a desktop background 
# xpmroot ~/background.xpm &

# automatically configure hotplugged USB keyboards 
watchexec -w /dev/input/by-id -d 300 -i ".*tmp.*" "bash -e /home/jephron/.bin/usb-keyboard-in" &

# automatically configure existing keyboards
bash -e /home/jephron/.bin/usb-keyboard-in

# # key-repeat delay and frequency
# xset r rate 200 40

# # make capslock into another control key
# setxkbmap -option ctrl:nocaps

exec xmonad

