#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f ~/.xprofile ] && . ~/.xprofile

# hide the mouse cursor when idle
unclutter -noevents -idle 2 &
#unclutter -noevents -idle 2 -grab &

# launch xmobar
xmobar &

# set key-repeat rate
xset r rate 200 40

# xpmroot ~/background.xpm &

exec xmonad


